# Install interesting packages.
#
# This assumes that the current user is the user used to install
# packages and has the proper administrator privileges.

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

# install interpreters prior to other packages
cask "adoptopenjdk"
# @todo use system python
#brew "python"
#brew "python3"
# @todo use system ruby
#brew "ruby"

# install version control systems
brew "git"

# install fuse
cask "osxfuse"
#brew "gitfs"
brew "sshfs"

#brew "arp-scan"
#brew "arp-sk"
#brew "arpoison"
brew "aspell"
#brew "avrdude"
#brew "avr-binutils"
#brew "avr-gcc"
brew "bash-completion"
brew "bear"
brew "boost"
brew "boost-bcp"
brew "boost-build"
brew "cflow"
brew "cmake"
brew "cmark-gfm"
brew "cppcheck"
brew "curl"
#brew "dfu-util"
brew "dita-ot"
brew "docbook"
brew "docbook-xsl"
brew "docker-completion"
brew "docker-compose-completion"
brew "docker-machine-completion"
brew "dos2unix"
brew "doxygen"
#brew "emscripten"
brew "enscript"
#brew "gcc"
brew "gcc@6"
brew "gcc@7"
brew "gcc@8"
brew "gcc@9"
brew "gdb"
brew "gem-completion"
brew "git-hooks"
brew "git-lfs"
brew "git-test"
brew "glew"
brew "glfw3"
brew "glm"
brew "global"
brew "glslang"
brew "gnu-typist"
brew "gnuplot"
brew "go"
brew "gpg"
brew "graphviz"
brew "guile"
brew "hadolint"
brew "highlight"
brew "htop-osx"
#brew "httping"
#brew "httpry"
brew "hub"
brew "iperf"
#brew "ipv6calc"
brew "jam"
brew "kubernetes-cli"
brew "launchctl-completion"
#brew "legit"
brew "llvm", args: ["HEAD"]
brew "llvm@6"
brew "llvm@7"
brew "llvm@8"
#brew "llvm@9"
brew "lua"
brew "luarocks"
brew "maven"
brew "maven-completion"
#brew "mscgen"
brew "netcat"
brew "netperf"
brew "nmap"
brew "node"
brew "nuttcp"
brew "open-completion"
brew "openssh"
brew "p0f"
brew "p7zip"
brew "pandoc"
#brew "parallel"
brew "pinentry"
brew "pip-completion"
brew "pkg-config"
brew "qemu"
#brew "rsync"
brew "ruby-completion"
brew "rust"
brew "rustc-completion"
brew "shellcheck"
brew "socat"
brew "sqlite"
#brew "srecord"
brew "ssh-copy-id"
brew "stdman"
brew "stow"
brew "swig"
brew "tcpdump"
#brew "tcpflow"
#brew "tcping"
#brew "tcpreplay"
#brew "tcptrace"
#brew "tcptraceroute"
#brew "tcptrack"
brew "terraform"
brew "tig"
brew "tmux"
brew "v8"
brew "vault"
brew "vagrant-completion"
#brew "vegeta"
#brew "vim"
brew "wget"
#brew "xctool"
brew "xmlformat"
brew "xmlstarlet"
brew "xmlto"
brew "zsh-completion"

cask "basictex"
cask "emacs"
cask "xquartz"
