# Install interesting packages.
#
# This assumes that the current user is the user used to install
# packages and has the proper administrator privileges.

brew "arm-none-eabi-binutils"
brew "arm-none-eabi-gcc"
brew "arm-none-eabi-gdb"
brew "aspell"
brew "bash-completion"
brew "boost"
brew "boost-bcp"
brew "boost-build"
brew "cmake"
brew "dict"
brew "dos2unix"
brew "emacs"
brew "emscripten"
brew "gcc"
# brew "gcc@7"
# brew "gcc@8"
# brew "gcc@9"
# brew "gcc@10"
brew "gcc@11"
brew "gcc@12"
brew "gcc@13"
brew "gcc@14"
brew "gdb"
brew "gh"
brew "git-filter-repo"
brew "git-lfs"
brew "gnuplot"
brew "go"
brew "gpg"
brew "guile"
brew "htop"
brew "jq"
brew "julia"
brew "launchctl-completion"
brew "llvm"
# brew "llvm@7"
# brew "llvm@8"
# brew "llvm@9"
# brew "llvm@10"
# brew "llvm@11"
# brew "llvm@12"
# brew "llvm@13"
brew "llvm@14"
brew "llvm@15"
brew "llvm@16"
brew "llvm@17"
brew "llvm@18"
brew "llvm@19"
brew "mit-scheme"
brew "node"
brew "open-completion"
brew "rust"
brew "rustc-completion"
brew "shellcheck"
brew "socat"
brew "stow"
brew "tig"
brew "zsh-completions"
