#!/bin/sh

set -e
set -u

if [ "$#" -gt 1 ]; then
    printf "usage: %s [branch]" "$0" 1>&2
    exit 1
fi

branch="${1:-master}"
rootdir="${HOME}"/opt/local/src/emacs

if [ ! -e "${rootdir}" ]; then
    printf "error: %s does not exist.\n" "${rootdir}" 1>&2
    exit 1
fi

packages=""
packages="${packages} libjansson-dev"
packages="${packages} librsvg2"
packages="${packages} libgnutls30"
packages="${packages} libgccjit-9-dev"

for package in ${packages} ; do
    if ! (apt list --installed | grep "${package}" > /dev/null) ; then
        printf "error: %s is not installed.\n" "${package}" 1>&2
        exit 1
    fi
done

git -C "${rootdir}" clean -q -d -x -f
git -C "${rootdir}" checkout "${branch}"
git -C "${rootdir}" clean -q -d -x -f
git -C "${rootdir}" reset --hard HEAD
git -C "${rootdir}" pull --ff-only origin "${branch}"

options=""
options="${options} --without-x"
options="${options} --with-gnutls"
options="${options} --with-json"
options="${options} --with-xml2"
options="${options} --with-rsvg"
options="${options} --with-native-compilation"

options="${options} --prefix="${HOME}"/opt/local"

(cd "${rootdir}" && ./autogen.sh)
(cd "${rootdir}" && ./configure ${options})
(cd "${rootdir}" && make -j 8)
(cd "${rootdir}" && make install)
