#!/bin/sh
#
# Install bootstrap packages for Fedora.
#
# This assumes that the current user is the user used to install
# packages and has the proper administrator privileges.

set -e
set -u

# Homebrew requirements
sudo yum groupinstall 'Development Tools' && sudo yum install curl file git

# Homebrew
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
