#!/usr/bin/env python
#
# Install Python modules in the python-packages.txt requirements file.

import site
import sys
import os
import subprocess
import distutils.spawn
import urllib2

python = distutils.spawn.find_executable("python")
pip = distutils.spawn.find_executable("pip")


def emulate_run(args, env=None):
    p = subprocess.Popen(args, env=env)
    if p.wait() == 0:
        return True
    return False

if not python:
    print "error: Python not installed, not installing Python packages."
    sys.exit(1)

if not pip:
    pippath = os.path.join(site.USER_BASE, "bin", "pip")
    if not os.path.exists(pippath):
        r = urllib2.urlopen("http://bootstrap.pypa.io/get-pip.py")
        with open("get-pip.py", "w") as f:
            f.write(r.read())

        if not os.path.exists("get-pip.py"):
            print "warning: pip failed to install, not installing Python packages."
            sys.exit(1)

        emulate_run([python, "get-pip.py", "--user"])
        os.remove("get-pip.py")

    if os.path.exists(pippath):
        pip = pippath

if not pip and not os.path.exists(pip):
    print "error: pip not installing, not installing Python packages."
    sys.exit(1)

sys.exit(emulate_run([pip, "install", "--user", "--upgrade", "-r", "python-packages.txt"]))
