#!/bin/sh
#
# Install interesting packages for Debian.
#
# This assumes that the current user is the user used to install
# packages and has the proper administrator privileges.

set -e
set -u

# additional repositories
#! @todo none right now

# install aptitude
sudo apt-get install aptitude

# package manager
pm=

# check if aptitude is installed
if [ -z "$(which aptitude 2> /dev/null)" ]; then
    echo "warning: aptitude not found"
else
    pm="sudo aptitude"
fi

# check if package manager is installed
if [ -z "${pm}" ]; then
    echo "error: Package manager not found."
    exit 1
fi

# update and check packages
${pm} update

# upgrade existing packages
${pm} safe-upgrade

# install packages for homedir installer
${pm} -y install wget
${pm} -y install stow
${pm} -y install diffutils

# install interpreters prior to other packages
${pm} -y install python
${pm} -y install python-dev
# @todo we don't need python3 at this point
#${pm} -y install python3
${pm} -y install ruby
${pm} -y install ruby-dev

# install version control systems
${pm} -y install git
${pm} -y install mercurial
${pm} -y install subversion

# install basic tools
${pm} -y install autoconf
${pm} -y install tar
${pm} -y install bzip2
${pm} -y install patch

# install fuse
#${pm} -y install gitfs
${pm} -y install sshfs

# install all taps with the right options
${pm} -y install arp-scan
#${pm} -y install arp-sk
#${pm} -y install arpoison
${pm} -y install avahi-autoipd
${pm} -y install avahi-daemon
${pm} -y install avahi-utils
#${pm} -y install avrdude
#${pm} -y install avr-binutils
#${pm} -y install avr-gcc
${pm} -y install bash-completion
#${pm} -y install bear
${pm} -y install libboost-dev
#${pm} -y install libboost-bcp-dev
${pm} -y install libboost-tools-dev
#${pm} -y install casperjs
${pm} -y install cflow
${pm} -y install clang
${pm} -y install cmake
${pm} -y install cppcheck
${pm} -y install dfu-util
#${pm} -y install dns2tcp
#${pm} -y install dnstop
#${pm} -y install docbook
#${pm} -y install docbook-xsl
#${pm} -y install docker
${pm} -y install doxygen
#${pm} -y install e2fsprogs
${pm} -y install emacs-nox
#${pm} -y install emscripten
${pm} -y install enscript
#${pm} -y install ext2fuse
#${pm} -y install fop
#${pm} -y install fortune
${pm} -y install gcc
${pm} -y install g++
#${pm} -y install gcc48
#${pm} -y install g++-4.8
#${pm} -y install gcc49
#${pm} -y install g++-4.9
#${pm} -y install gcc5
#${pm} -y install g++-5
#${pm} -y install gcc6
#${pm} -y install g++-6
${pm} -y install gdb
#${pm} -y install gem-completion
#${pm} -y install git-flow
#${pm} -y install git-hooks
#${pm} -y install git-lfs
${pm} -y install git-svn
#${pm} -y install git-test
#${pm} -y install glew
#${pm} -y install glfw3
#${pm} -y install glib
#${pm} -y install glm
${pm} -y install global
#${pm} -y install glslang
#${pm} -y install gnu-typist
${pm} -y install golang
#${pm} -y install graphviz
${pm} -y install guile-2.0
${pm} -y install highlight
${pm} -y install htop
#${pm} -y install httping
#${pm} -y install httpry
${pm} -y install hunspell
${pm} -y install iperf
${pm} -y install ipv6calc
${pm} -y install jam
#${pm} -y install jansson
#${pm} -y install jasper
#${pm} -y install jpeg
#${pm} -y install jrnl
#${pm} -y install jsl
#${pm} -y install jsmin
#${pm} -y install json-c
#${pm} -y install jsonpp
#${pm} -y install launchctl-completion
#${pm} -y install legit
${pm} -y install libclang-dev
${pm} -y install libnss-mdns
#${pm} -y install lldb
#${pm} -y install lld
${pm} -y install llvm
#${pm} -y install llvm35
#${pm} -y install llvm36
#${pm} -y install llvm37
#${pm} -y install llvm38
${pm} -y install llvm-dev
${pm} -y install llvm-runtime
${pm} -y install lrzsz
#${pm} -y install markdown
#${pm} -y install mscgen
#${pm} -y install netcat
#${pm} -y install netperf
${pm} -y install nmap
${pm} -y install nodejs
${pm} -y install nodejs-dev
${pm} -y install npm
#${pm} -y install ntfs-3g
${pm} -y install ntp
${pm} -y install nuttcp
#${pm} -y install open-completion
${pm} -y install openocd
#${pm} -y install osxfuse
#${pm} -y install p0f
#${pm} -y install p7zip
#${pm} -y install parallel
#${pm} -y install phantomjs
#${pm} -y install pinentry
#${pm} -y install pip-completion
#${pm} -y install pkg-config
#${pm} -y install ruby-completion
${pm} -y install screen
${pm} -y install shellcheck
${pm} -y install sloccount
${pm} -y install socat
${pm} -y install sqlite
${pm} -y install srecord
#${pm} -y install ssh-copy-id
#${pm} -y install stdman
${pm} -y install stow
#${pm} -y install stress
#${pm} -y install subgit
#${pm} -y install swig
${pm} -y install tcpdump
#${pm} -y install tcpflow
#${pm} -y install tcping
${pm} -y install tcpreplay
#${pm} -y install tcptrace
${pm} -y install tcptraceroute
${pm} -y install tcptrack
#${pm} -y install termshare
${pm} -y install tig
${pm} -y install tmux
${pm} -y install tree
#${pm} -y install v8
#${pm} -y install vegeta
${pm} -y install vim
#${pm} -y install webp
${pm} -y install wget
#${pm} -y install wireshark
#${pm} -y install xctool
#${pm} -y install xmlformat
#${pm} -y install xmlstarlet
#${pm} -y install xmlto

# cleanup
sudo apt-get autoremove
${pm} clean
${pm} autoclean
