#!/usr/bin/env python
#
# Install Node packages in the node-packages.txt package list.

import sys
import os
import subprocess
import distutils.spawn


def emulate_run(s):
    if subprocess.call(s, shell=True) == 0:
        return True
    return False


def emulate_backtick(s):
    try:
        output = subprocess.check_output(s, shell=True).rstrip("\n")
    except:
        output = ""

    return output

HOME = os.environ["HOME"]

node = distutils.spawn.find_executable("node")
if not node:
    node = distutils.spawn.find_executable("nodejs")
    if not node:
        print "error: node is not installed, skipping node module installation"
        sys.exit(1)

npm = distutils.spawn.find_executable("npm")
if not npm:
    print "error: npm is not installed, skipping node module installation"
    sys.exit(1)

node_packages = emulate_backtick("grep -v \"^#\" node-packages.txt")
for m in node_packages.split():
    emulate_run(npm + " install --global --prefix=\"" + os.path.join(HOME, ".node_modules") + "\" \"" + m + "\"")
