#!/bin/sh
#
# Install interesting packages for OS X.
#
# This assumes that the current user is the user used to install brews
# and has the proper administrator privileges.

# required homebrew taps
brew_taps="
    homebrew/apache
    homebrew/binary
    homebrew/completions
    homebrew/dupes
    homebrew/headonly
    homebrew/nginx
    homebrew/python
    homebrew/science
    homebrew/versions
"

# check if Homebrew is installed
if [ -z "$(which brew)" ]; then
    echo "error: Homebrew (brew) not found."
    exit 1
fi

# update Homebrew and run doctor
brew update
brew doctor

# make sure git is installed early
brew install git
brew update

# re-tap all taps and update Homebrew
for t in $(brew tap) ; do brew untap "${t}" ; done
brew update
for t in ${brew_taps} ; do brew tap "${t}" ; done
brew update

# install interpreters prior to other brews
brew install python
brew install python3
brew install ruby

# install version control systems
brew install bazaar
brew install git
brew install mercurial
brew install subversion17 --with-python --perl

# install all taps with the right options
brew install arp-scan
brew install arp-sk
brew install arpoison
brew install autoconf
brew install automake
#brew install avrdude
#brew install avr-binutils
#brew install avr-gcc
brew install boost
#brew install boost-bcp
#brew install boost-build
brew install casperjs
brew install cmake
brew install cppcheck
brew install dart
brew install dns2tcp
brew install dnstop
brew install docbook
brew install docbook-xsl
brew install docker
brew install doxygen --with-dot --with-libclang
brew install e2fsprogs
brew install emacs --cocoa
brew install emscripten
brew install enscript
brew install ext2fuse
brew install fop
brew install fortune
brew install apple-gcc42
HOMEBREW_KEEP_INFO=1 brew install gcc
brew install gcc43 --enable-all-languages
# @todo conflicts with gcc45
#brew install gcc44 --enable-all-languages
brew install gcc45 --enable-all-languages
brew install gcc46 --enable-all-languages
brew install gcc47 --enable-all-languages
brew install gcc48 --enable-all-languages
# @todo conflicts with gcc
#brew install gcc49 --enable-all-languages
brew install git-flow
brew install git-hooks --HEAD
brew install glew
brew install glfw3
brew install glib
brew install glm
HOMEBREW_KEEP_INFO=1 brew install global --with-exuberant-ctags
HOMEBREW_KEEP_INFO=1 brew install gnu-typist
brew install go --cross-compile-all
brew install gource
brew install graphviz
HOMEBREW_KEEP_INFO=1 brew install guile --devel
brew install highlight
brew install htop-osx
brew install httping
brew install httpry
brew install hunspell
brew install iperf
brew install ipv6calc
brew install jam
brew install jansson
brew install jasper
brew install jpeg
brew install jsdoc-toolkit
brew install jsl
brew install jsmin
brew install json-c
brew install jsonpp
brew install legit
# @note this installs the llvm library, keg-only
brew install llvm
brew install llvm31 --all-targets --with-clang
# @todo does not build
#brew install llvm32 --all-targets --with-asan --with-clang
brew install llvm33 --all-targets --with-asan --with-clang --with-libcxx --rtti
brew install llvm34 --all-targets --with-asan --with-clang --with-libcxx --rtti
brew install llvm35 --all-targets --with-asan --with-clang --with-libcxx --rtti
brew install markdown
brew install multimarkdown
brew install mscgen --without-gd
brew install netcat
brew install netperf
brew install nmap
brew install node
brew install nuttcp
brew install ntfs-3g
brew install osxfuse
brew install nuttcp
brew install p0f
brew install p7zip
brew install parallel
brew install phantomjs
brew install pinentry
brew install pkg-config
brew install socat
brew install sqlite --with-docs
brew install srecord
brew install ssh-copy-id
brew install sshfs
brew install stow
brew install stress
brew install subgit
brew install swig
brew install tcpdump
brew install tcpflow
brew install tcping
brew install tcpreplay
brew install tcptrace
brew install tcptraceroute
brew install tcptrack
brew install termshare
brew install tig
brew install tmux
brew install tree
brew install v8
brew install webp
brew install wget
brew install wireshark
brew install xctool
brew install xmlformat
brew install xmlstarlet
brew install xmlto

# cleanup
brew cleanup -s

# show outdated brews
outdated=$(brew outdated)
if [ ! -z "${outdated}" ]; then
    echo "info: outdated brews, consider running 'brew upgrade'"
    for b in ${outdated}; do
        echo "\t${b}"
    done
fi
