#!/bin/sh
#
# Install interesting packages for Fedora.
#
# This assumes that the current user is the user used to install
# packages and has the proper administrator privileges.

set -e
set -u

release=$(cat /etc/fedora-release)
version=0
if [ "${release}" = "Fedora release 22 (Twenty Two)" ]; then
    version=22
elif [ "${release}" = "Fedora release 23 (Twenty Three)" ]; then
    version=23
elif [ "${release}" = "Fedora release 24 (Twenty Four)" ]; then
    version=24
elif [ "${release}" = "Fedora release 25 (Twenty Four)" ]; then
    version=25
elif [ "${release}" = "Fedora release 26 (Twenty Four)" ]; then
    version=26
fi

# package manager
pm=
pm_check=
pm_update=
pm_upgrade=
pm_install=
pm_cleanup=

# check if dnf is installed
if [ -z "$(which dnf 2> /dev/null)" ]; then
    echo "warning: dnf not found."
else
    pm="dnf"
    pm_check="true"
    pm_update="sudo ${pm} update"
    pm_upgrade="true"
    pm_install="sudo ${pm} -q -y install"
    pm_cleanup="sudo ${pm} autoremove"

    sudo ${pm} install dnf-plugins-core
    sudo ${pm} config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
fi

# check if yum is installed, if package manager is not
if [ -z "${pm}" ]; then
    if [ -z "$(which yum 2> /dev/null)" ]; then
        echo "warning: yum not found."
    else
        pm="yum"
        pm_check="true"
        pm_update="sudo ${pm} update"
        pm_upgrade="true"
        pm_install="sudo ${pm} -q -y install"
        pm_cleanup="sudo ${pm} autoremove && ${pm} clean all"
    fi
fi

# check if package manager is installed
if [ -z "${pm}" ]; then
    echo "error: Package manager not found."
    exit 1
fi

# additional repositories
${pm_install} curl

curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | sudo bash

# update and check packages
${pm_update}
if ! ${pm_check} ; then
    echo "warning: Package manager check failed, continue anyway (y/n)?: \c"
    read -r yn
    if [ "${yn}" != "y" ]; then
	exit 1
    fi
fi
${pm_update}

# upgrade existing packages
${pm_upgrade}

# install packages for homedir installer
${pm_install} wget
${pm_install} stow
${pm_install} diffutils

# install interpreters prior to other packages
${pm_install} python
${pm_install} python-devel
${pm_install} python3
${pm_install} python3-devel
${pm_install} ruby
${pm_install} ruby-devel

# install version control systems
${pm_install} git
${pm_install} subversion

# install basic tools
${pm_install} autoconf
${pm_install} tar
${pm_install} bzip2
${pm_install} patch

# install fuse
#${pm_install} gitfs
${pm_install} sshfs

# install all taps with the right options
${pm_install} arp-scan
#${pm_install} arp-sk
#${pm_install} arpoison
${pm_install} avahi
${pm_install} avahi-tools
#${pm_install} avrdude
${pm_install} avr-binutils
${pm_install} avr-gcc
${pm_install} bash-completion
#${pm_install} bear
${pm_install} boost
#${pm_install} boost-bcp
${pm_install} boost-build
${pm_install} boost-devel
#${pm_install} casperjs
${pm_install} cflow
${pm_install} clang
${pm_install} clang-devel
${pm_install} clang-libs
#${pm_install} clblas
#${pm_install} clfft
#${pm_install} clinfo
${pm_install} cmake
${pm_install} cppcheck
${pm_install} dfu-util
#${pm_install} dns2tcp
#${pm_install} dnstop
#${pm_install} docbook
#${pm_install} docbook-xsl
#${pm_install} docker-ce
${pm_install} doxygen
#${pm_install} e2fsprogs
${pm_install} emacs-nox
#${pm_install} emscripten
${pm_install} enscript
#${pm_install} ext2fuse
#${pm_install} fop
#${pm_install} fortune
${pm_install} gcc
${pm_install} gcc-c++
#${pm_install} gcc48
#${pm_install} gcc48-c++
#${pm_install} gcc49
#${pm_install} gcc49-c++
#${pm_install} gcc5
#${pm_install} gcc5-c++
#${pm_install} gcc6
#${pm_install} gcc6-c++
${pm_install} gdb
#${pm_install} gem-completion
${pm_install} git-extras
#${pm_install} git-flow
#${pm_install} git-hooks
${pm_install} git-lfs
${pm_install} git-svn
#${pm_install} git-test
#${pm_install} github-desktop
#${pm_install} glew
#${pm_install} glfw3
#${pm_install} glib
#${pm_install} glm
${pm_install} global
#${pm_install} glslang
#${pm_install} gnu-typist
${pm_install} golang
${pm_install} gnupg
#${pm_install} graphviz
${pm_install} guile
#${pm_install} hadolint
${pm_install} hdf5
${pm_install} hdf5-devel
${pm_install} highlight
${pm_install} htop
#${pm_install} httping
#${pm_install} httpry
${pm_install} hunspell
${pm_install} iperf
${pm_install} ipv6calc
${pm_install} jam
${pm_install} libasan
${pm_install} libasan-static
#${pm_install} jansson
#${pm_install} jasper
#${pm_install} jpeg
#${pm_install} jrnl
#${pm_install} jsl
#${pm_install} jsmin
#${pm_install} json-c
#${pm_install} jsonpp
#${pm_install} kubernetes-cli
#${pm_install} legit
${pm_install} llvm
#${pm_install} llvm35
#${pm_install} llvm36
#${pm_install} llvm37
#${pm_install} llvm38
#${pm_install} llvm39
#${pm_install} llvm4
${pm_install} llvm-devel
${pm_install} lrzsz
#${pm_install} markdown
${pm_install} maven
#${pm_install} mscgen
#${pm_install} netcat
#${pm_install} netperf
${pm_install} nmap
${pm_install} nodejs
if [ "${version}" -ge 24 ]; then
    ${pm_install} npm
fi
${pm_install} nss-mdns
#${pm_install} ntfs-3g
${pm_install} ntp
${pm_install} nuttcp
#${pm_install} open-completion
${pm_install} openocd
#${pm_install} osxfuse
#${pm_install} p0f
#${pm_install} p7zip
#${pm_install} parallel
#${pm_install} phantomjs
#${pm_install} pinentry
#${pm_install} pip-completion
#${pm_install} pkg-config
${pm_install} protobuf
#${pm_install} ruby-completion
${pm_install} screen
${pm_install} ShellCheck
${pm_install} sloccount
${pm_install} socat
${pm_install} sqlite
${pm_install} srecord
#${pm_install} ssh-copy-id
#${pm_install} stdman
${pm_install} stow
#${pm_install} stress
#${pm_install} subgit
#${pm_install} swig
${pm_install} tcpdump
#${pm_install} tcpflow
${pm_install} tcping
${pm_install} tcpreplay
#${pm_install} tcptrace
${pm_install} tcptraceroute
${pm_install} tcptrack
#${pm_install} termshare
${pm_install} texlive-scheme-basic
${pm_install} tig
${pm_install} tmux
${pm_install} tree
${pm_install} unzip
#${pm_install} vault
${pm_install} v8
#${pm_install} vegeta
${pm_install} vim
#${pm_install} webp
${pm_install} wget
#${pm_install} wireshark
#${pm_install} xctool
#${pm_install} xmlformat
#${pm_install} xmlstarlet
#${pm_install} xmlto

# cleanup
${pm_cleanup}
