#!/bin/sh
#
# Install interesting packages for OS X.
#
# This assumes that the current user is the user used to install
# packages.  and has the proper administrator privileges.

set -e
set -u

# additional repositories
brew_taps="
    homebrew/apache
    homebrew/binary
    homebrew/completions
    dart-lang/dart
    homebrew/dupes
    homebrew/fuse
    homebrew/headonly
    homebrew/nginx
    homebrew/python
    homebrew/science
    homebrew/tex
    homebrew/versions
"

# check if Homebrew is installed
if [ -z "$(which brew 2> /dev/null)" ]; then
    echo "error: Homebrew (brew) not found."
    exit 1
fi

# update and check packages
brew update
brew doctor

# upgrade all installed packages
brew update
brew upgrade --all

# make sure git is installed early
brew install git
brew update

# re-tap all taps and update Homebrew
for t in $(brew tap) ; do brew untap "${t}" ; done
brew update
for t in ${brew_taps} ; do brew tap "${t}" ; done
brew update

# upgrade existing packages
brew upgrade --all

# install interpreters prior to other packages
# @todo use system python
#brew install python
# @todo we don't need python3 at this point
#brew install python3
# @todo use system ruby
#brew install ruby

# install version control systems
brew install bazaar
brew install git
brew install mercurial
brew install subversion17

# install all taps with the right options
brew install arp-scan
brew install arp-sk
brew install arpoison
brew install autoconf
brew install automake
#brew install avrdude
#brew install avr-binutils
#brew install avr-gcc
brew install bash-completion
brew install bear
brew install boost
#brew install boost-bcp
brew install boost-build
brew install casperjs
brew install clang-format
brew install cmake
brew install cppcheck
brew install cups-pdf
brew install dart
brew install dns2tcp
brew install dnstop
brew install docbook
brew install docbook-xsl
brew install docker
brew install doxygen
brew install e2fsprogs
brew install emacs --with-cocoa
brew install emscripten
brew install enscript
#brew install ext2fuse
brew install fop
brew install fortune
#HOMEBREW_KEEP_INFO=1 brew install gcc
#brew install gcc43
#brew install gcc44
brew install gcc45
brew install gcc46
brew install gcc47
brew install gcc48
brew install gcc49
HOMEBREW_KEEP_INFO=1 brew install gcc5
brew install git-flow
brew install git-hooks
brew install git-lfs
brew install git-test
brew install glew
brew install glfw3
brew install glib
brew install glm
HOMEBREW_KEEP_INFO=1 brew install global --with-exuberant-ctags
HOMEBREW_KEEP_INFO=1 brew install gnu-typist
brew install go
brew install gource
brew install graphviz
HOMEBREW_KEEP_INFO=1 brew install guile
brew install highlight
brew install htop-osx
brew install httping
brew install httpry
brew install hunspell
brew install iperf
brew install ipv6calc
brew install jam
brew install jansson
brew install jasper
brew install jpeg
brew install jrnl
brew install jsdoc-toolkit
brew install jsl
brew install jsmin
brew install json-c
brew install jsonpp
brew install legit
brew install llvm
brew install llvm33
brew install llvm34
brew install llvm35
brew install markdown
#brew install mscgen --without-gd
brew install netcat
brew install netperf
brew install nmap
brew install node
brew install nuttcp
#brew install ntfs-3g
#brew install osxfuse
brew install nuttcp
brew install openocd
brew install p0f
brew install p7zip
brew install parallel
brew install phantomjs
brew install pinentry
brew install pkg-config
brew install shellcheck
brew install socat
brew install sqlite
brew install srecord
brew install ssh-copy-id
#brew install sshfs
brew install stow
brew install stress
brew install subgit
brew install swig
brew install tcpdump
brew install tcpflow
brew install tcping
brew install tcpreplay
brew install tcptrace
brew install tcptraceroute
brew install tcptrack
brew install termshare
brew install tig
brew install tmux
brew install tree
brew install v8
brew install vegeta
brew install vim
brew install webp
brew install wget
#brew install wireshark
brew install xctool
brew install xmlformat
brew install xmlstarlet
brew install xmlto

# cleanup
brew cleanup -s
