#!/bin/sh
#
# Install interesting packages for Debian.
#
# This assumes that the current user is the user used to install
# packages and has the proper administrator privileges.

set -e
set -u

# additional repositories
#! @todo none right now

# install aptitude
sudo apt-get install aptitude

# check if aptitude is installed
if [ -z "$(which aptitude 2> /dev/null)" ]; then
    echo "error: aptitude not found."
    exit 1
fi

# update and check packages
sudo aptitude update

# upgrade existing packages
sudo aptitude safe-upgrade

# install packages for homedir installer
sudo aptitude -y install wget
sudo aptitude -y install stow
sudo aptitude -y install diffutils

# install interpreters prior to other packages
sudo aptitude -y install python
sudo aptitude -y install python-dev
# @todo we don't need python3 at this point
#sudo aptitude -y install python3
sudo aptitude -y install ruby
sudo aptitude -y install ruby-dev

# install version control systems
sudo aptitude -y install git
sudo aptitude -y install mercurial
sudo aptitude -y install subversion

# install basic tools
sudo aptitude -y install autoconf
sudo aptitude -y install tar
sudo aptitude -y install bzip2
sudo aptitude -y install patch

# install fuse
#sudo aptitude -y install gitfs
sudo aptitude -y install sshfs

# install all taps with the right options
sudo aptitude -y install arp-scan
#sudo aptitude -y install arp-sk
#sudo aptitude -y install arpoison
sudo aptitude -y install avahi-daemon
#sudo aptitude -y install avrdude
#sudo aptitude -y install avr-binutils
#sudo aptitude -y install avr-gcc
sudo aptitude -y install bash-completion
#sudo aptitude -y install bear
#sudo aptitude -y install boost
#sudo aptitude -y install boost-bcp
sudo aptitude -y install boost-build
#sudo aptitude -y install casperjs
sudo aptitude -y install cflow
sudo aptitude -y install clang
sudo aptitude -y install cmake
sudo aptitude -y install cppcheck
#sudo aptitude -y install dns2tcp
#sudo aptitude -y install dnstop
#sudo aptitude -y install docbook
#sudo aptitude -y install docbook-xsl
#sudo aptitude -y install docker
sudo aptitude -y install doxygen
#sudo aptitude -y install e2fsprogs
sudo aptitude -y install emacs-nox
#sudo aptitude -y install emscripten
sudo aptitude -y install enscript
#sudo aptitude -y install ext2fuse
#sudo aptitude -y install fortune
sudo aptitude -y install gcc
sudo aptitude -y install g++
#sudo aptitude -y install gcc48
#sudo aptitude -y install g++-4.8
#sudo aptitude -y install gcc49
#sudo aptitude -y install g++-4.9
#sudo aptitude -y install gcc5
#sudo aptitude -y install g++-5
#sudo aptitude -y install git-flow
#sudo aptitude -y install git-hooks
#sudo aptitude -y install git-lfs
#sudo aptitude -y install git-test
#sudo aptitude -y install glew
#sudo aptitude -y install glfw3
#sudo aptitude -y install glib
#sudo aptitude -y install glm
sudo aptitude -y install global
#sudo aptitude -y install glslang
#sudo aptitude -y install gnu-typist
sudo aptitude -y install golang
#sudo aptitude -y install graphviz
sudo aptitude -y install guile-2.0
sudo aptitude -y install highlight
#sudo aptitude -y install htop-osx
#sudo aptitude -y install httping
#sudo aptitude -y install httpry
sudo aptitude -y install hunspell
sudo aptitude -y install iperf
sudo aptitude -y install ipv6calc
sudo aptitude -y install jam
#sudo aptitude -y install jansson
#sudo aptitude -y install jasper
#sudo aptitude -y install jpeg
#sudo aptitude -y install jrnl
#sudo aptitude -y install jsl
#sudo aptitude -y install jsmin
#sudo aptitude -y install json-c
#sudo aptitude -y install jsonpp
#sudo aptitude -y install legit
sudo aptitude -y install llvm
#sudo aptitude -y install llvm35
#sudo aptitude -y install llvm36
sudo aptitude -y install lrzsz
#sudo aptitude -y install markdown
#sudo aptitude -y install mscgen
#sudo aptitude -y install netcat
#sudo aptitude -y install netperf
sudo aptitude -y install nmap
sudo aptitude -y install nodejs
sudo aptitude -y install nodejs-dev
sudo aptitude -y install npm
sudo aptitude -y install ntp
sudo aptitude -y install nuttcp
sudo aptitude -y install openocd
#sudo aptitude -y install osxfuse
#sudo aptitude -y install nuttcp
#sudo aptitude -y install p0f
#sudo aptitude -y install p7zip
#sudo aptitude -y install parallel
#sudo aptitude -y install phantomjs
#sudo aptitude -y install pinentry
#sudo aptitude -y install pkg-config
sudo aptitude -y install screen
sudo aptitude -y install shellcheck
sudo aptitude -y install sloccount
sudo aptitude -y install socat
sudo aptitude -y install sqlite
sudo aptitude -y install srecord
#sudo aptitude -y install ssh-copy-id
#sudo aptitude -y install stdman
sudo aptitude -y install stow
#sudo aptitude -y install stress
#sudo aptitude -y install subgit
#sudo aptitude -y install swig
sudo aptitude -y install tcpdump
#sudo aptitude -y install tcpflow
#sudo aptitude -y install tcping
sudo aptitude -y install tcpreplay
#sudo aptitude -y install tcptrace
sudo aptitude -y install tcptraceroute
sudo aptitude -y install tcptrack
#sudo aptitude -y install termshare
sudo aptitude -y install tig
sudo aptitude -y install tmux
sudo aptitude -y install tree
#sudo aptitude -y install v8
#sudo aptitude -y install vegeta
sudo aptitude -y install vim
#sudo aptitude -y install webp
sudo aptitude -y install wget
#sudo aptitude -y install wireshark
#sudo aptitude -y install xctool
#sudo aptitude -y install xmlformat
#sudo aptitude -y install xmlstarlet
#sudo aptitude -y install xmlto

# cleanup
sudo apt-get autoremove
sudo aptitude clean
sudo aptitude autoclean
