#!/bin/sh
#
# Install interesting packages for OS X.
#
# This assumes that the current user is the user used to install
# packages and has the proper administrator privileges.

set -e
set -u

# package manager
pm=
pm_check=
pm_update=
pm_upgrade=
pm_install=
pm_cleanup=

# check if Homebrew is installed
if [ -z "$(which brew 2> /dev/null)" ]; then
    echo "warning: Homewbrew (brew) not found."
else
    pm="brew"
    pm_check="${pm} doctor"
    pm_update="${pm} update"
    pm_upgrade="${pm} upgrade"
    pm_install="${pm} install"
    pm_cleanup="${pm} cleanup -s"
    pm_cask_install="${pm} cask install"
fi

# check if package manager is installed
if [ -z "${pm}" ]; then
    echo "error: Package manager not found."
    exit 1
fi

# update and check packages
${pm_update}
if ! ${pm_check} ; then
    echo "warning: Package manager check failed, continue anyway (y/n)?: \c"
    read -r yn
    if [ "${yn}" != "y" ]; then
	exit 1
    fi
fi
${pm_update}

# upgrade existing packages
${pm_upgrade}
# @todo work this into environment variables
if [ "$(brew cask outdated)" != "" ]; then
    brew cask reinstall $(brew cask outdated)
fi

# install interpreters prior to other packages
# @todo use system python
#${pm_install} python
${pm_install} python3
# @todo use system ruby
#${pm_install} ruby

# install version control systems
${pm_install} bazaar
${pm_install} git
${pm_install} subversion

# install fuse
${pm_cask_install} osxfuse
#${pm_install} gitfs
${pm_install} sshfs

${pm_cask_install} 1password
${pm_install} arp-scan
${pm_install} arp-sk
${pm_install} arpoison
${pm_install} aspell
#${pm_install} avrdude
#${pm_install} avr-binutils
#${pm_install} avr-gcc
${pm_install} bash-completion
${pm_install} bear
${pm_install} boost
${pm_install} boost-bcp
${pm_install} boost-build
#${pm_install} casperjs
${pm_cask_install} chef/chef/chefdk
${pm_install} cflow
${pm_install} clblas
${pm_install} clfft
${pm_install} clinfo
${pm_install} cmake
${pm_install} cppcheck
${pm_install} curl
${pm_install} dfu-util
${pm_install} dns2tcp
${pm_install} dnstop
${pm_install} docbook
${pm_install} docbook-xsl
${pm_cask_install} docker
${pm_install} doxygen
${pm_install} emacs --with-cocoa
${pm_install} emscripten
${pm_install} enscript
#${pm_install} ext2fuse
${pm_install} fortune
${pm_install} gcc
#${pm_install} gcc@4.6
#${pm_install} gcc@4.7
#${pm_install} gcc@4.8
#${pm_install} gcc@4.9
#${pm_install} gcc@5
${pm_install} gcc@6
${pm_install} gcc@7
${pm_install} gdb
${pm_install} gem-completion
${pm_install} git-flow
${pm_install} git-hooks
${pm_install} git-lfs
${pm_install} git-test
${pm_cask_install} github
${pm_install} glew
${pm_install} glfw3
${pm_install} glib
${pm_install} glm
${pm_install} global --with-exuberant-ctags
${pm_install} glslang
${pm_install} gnu-typist
${pm_install} gnuplot
${pm_install} go
${pm_install} gpg
${pm_cask_install} google-chrome
${pm_cask_install} google-drive-file-stream
${pm_install} graphviz
${pm_install} guile
${pm_install} hadolint
${pm_install} hdf5
${pm_install} highlight
${pm_install} htop-osx
${pm_install} httping
${pm_install} httpry
${pm_install} iperf
${pm_install} ipv6calc
${pm_install} jam
${pm_install} jansson
${pm_install} jasper
${pm_cask_install} java
${pm_install} jpeg
${pm_install} jrnl
#${pm_install} jsl
${pm_install} jsmin
${pm_install} json-c
${pm_install} jsonpp
${pm_install} kubernetes-cli
${pm_install} launchctl-completion
${pm_install} legit
${pm_install} llvm
${pm_install} llvm@3.9
${pm_install} llvm@4
${pm_install} llvm@5
${pm_install} llvm@6
${pm_install} lrzsz
${pm_install} markdown
${pm_install} maven
${pm_install} maven-completion
#${pm_install} mscgen --without-gd
${pm_install} netcat
${pm_install} netperf
${pm_install} nmap
${pm_install} node
#${pm_install} ntfs-3g
${pm_install} nuttcp
#${pm_cask_install} homebrew/cask-drivers/nvidia-cuda
${pm_install} open-completion
${pm_install} openocd
#${pm_install} osxfuse
${pm_install} p0f
${pm_install} p7zip
${pm_install} parallel
#${pm_install} phantomjs
${pm_install} pinentry
${pm_install} pip-completion
${pm_install} pkg-config
${pm_install} protobuf
#${pm_install} rsync
${pm_install} ruby-completion
${pm_install} rust
${pm_install} shellcheck
${pm_cask_install} slack
${pm_install} sloccount
${pm_install} socat
${pm_cask_install} sourcetree
${pm_install} sqlite
${pm_install} srecord
${pm_install} ssh-copy-id
${pm_install} stdman
${pm_install} stow
${pm_install} stress
${pm_cask_install} subgit
${pm_install} swig
${pm_install} tcpdump
${pm_install} tcpflow
${pm_install} tcping
${pm_install} tcpreplay
${pm_install} tcptrace
${pm_install} tcptraceroute
#${pm_install} tcptrack
${pm_install} termshare
${pm_install} terraform
${pm_cask_install} thunderbird
${pm_cask_install} basictex
${pm_install} tig
${pm_install} tmux
${pm_install} tree
${pm_install} v8
${pm_install} vault
#${pm_install} vegeta
#${pm_install} vim
${pm_install} webp
${pm_install} wget
#${pm_install} wireshark
#${pm_install} xctool
${pm_install} xmlformat
${pm_install} xmlstarlet
${pm_install} xmlto
${pm_cask_install} xquartz

# cleanup
${pm_cleanup}
