#!/usr/bin/env python
#
# Install Node packages in the node-packages.txt package list.

import sys
import os
import subprocess
import distutils.spawn


def emulate_run(args, env=None):
    p = subprocess.Popen(args, env=env)
    if p.wait() == 0:
        return True
    return False

HOME = os.environ["HOME"]

node = distutils.spawn.find_executable("node")
if not node:
    node = distutils.spawn.find_executable("nodejs")
    if not node:
        print "error: node is not installed, skipping node module installation"
        sys.exit(1)

npm = distutils.spawn.find_executable("npm")
if not npm:
    print "error: npm is not installed, skipping node module installation"
    sys.exit(1)

error = False
with open("node-packages.txt", "r") as f:
    for line in f:
        if line != "" and line[0] != "#":
            if not emulate_run([npm, "install", "--global", "--prefix", os.path.join(HOME, ".node_modules"), line]):
                error = True

sys.exit(1 if error else 0)
