#!/bin/sh
#
# Install interesting Python packages from pip.

# check if Python is installed
if [ -z "$(which python)" ]; then
    echo "error: Python not found."
    exit 1
fi

# check if pip is installed
# @todo install pip using normal methods
if [ -z "$(which pip)" ]; then
    echo "error: pip is not found."
    exit 1
fi

# install packages manually
#pip install beets
#pip install breathe
pip install docutils
pip install flake8
pip install jedi
#pip install pycparser
#pip install pyflakes
#pip install pygit2
#pip install PyGithub
pip install Sphinx
pip install virtualenv
