#!/bin/sh
#
# Install interesting packages for OS X.
#
# This assumes that the current user is the user used to install
# packages and has the proper administrator privileges.

set -e
set -u

# package manager
pm=

# additional repositories
brew_taps="
    homebrew/apache
    homebrew/binary
    homebrew/completions
    homebrew/dupes
    homebrew/fuse
    homebrew/headonly
    homebrew/nginx
    homebrew/python
    homebrew/science
    homebrew/tex
    homebrew/versions
"

# check if Homebrew is installed
if [ -z "$(which brew 2> /dev/null)" ]; then
    echo "warning: Homewbrew (brew) not found."
else
    pm="brew"
fi

# check if package manager is installed
if [ -z "${pm}" ]; then
    echo "error: Package manager not found."
    exit 1
fi

# update and check packages
${pm} update
if ! ${pm} doctor ; then
    echo "${pm} doctor failed, continue anyway (y/n)?: \c"
    read -r yn
    if [ "${yn}" != "y" ]; then
	exit 1
    fi
fi

# upgrade all installed packages
${pm} update
${pm} upgrade --all

# make sure git is installed early
${pm} install git
${pm} update

# notify of unspecified taps
for t0 in $(${pm} tap) ; do
    present=false
    for t1 in ${brew_taps} ; do
        if [ "${t0}" = "${t1}" ]; then
            present=true
        fi
    done

    if [ "${present}" = "false" ]; then
        echo "warning: tap ${t0} is unspecified."
    fi
done

# tap any missing taps and repair all taps
for t0 in ${brew_taps} ; do
    present=false
    for t1 in $(${pm} tap) ; do
        if [ "${t0}" = "${t1}" ]; then
            present=true
        fi
    done

    if [ "${present}" = "false" ]; then
        ${pm} tap --full "${t0}"
    fi
done
${pm} update

# repair all taps
for t in $(${pm} tap) ; do
    ${pm} tap --repair "${t}"
done
${pm} update

# upgrade existing packages
${pm} upgrade --all

# install interpreters prior to other packages
# @todo use system python
#${pm} install python
# @todo we don't need python3 at this point
#${pm} install python3
# @todo use system ruby
#${pm} install ruby

# install version control systems
${pm} install bazaar
${pm} install git
${pm} install mercurial
${pm} install subversion

# install fuse
#${pm} install gitfs
${pm} install sshfs

# install all taps with the right options
${pm} install arp-scan
${pm} install arp-sk
${pm} install arpoison
#${pm} install avrdude
#${pm} install avr-binutils
#${pm} install avr-gcc
${pm} install bash-completion
${pm} install bear
${pm} install boost
#${pm} install boost-bcp
${pm} install boost-build
${pm} install casperjs
${pm} install cflow
${pm} install cmake
${pm} install cppcheck
${pm} install dfu-util
${pm} install dns2tcp
${pm} install dnstop
${pm} install docbook
${pm} install docbook-xsl
${pm} install docker
${pm} install doxygen
${pm} install emacs --with-cocoa
${pm} install emscripten
${pm} install enscript
#${pm} install ext2fuse
${pm} install fortune
${pm} install gcc
${pm} install gcc48
${pm} install gcc49
${pm} install gcc5
#${pm} install gcc6
${pm} install gdb
${pm} install gem-completion
${pm} install git-flow
${pm} install git-hooks
${pm} install git-lfs
${pm} install git-test
${pm} install glew
${pm} install glfw3
${pm} install glib
${pm} install glm
${pm} install global --with-exuberant-ctags
${pm} install glslang
${pm} install gnu-typist
${pm} install go
${pm} install graphviz
${pm} install guile
${pm} install highlight
${pm} install htop-osx
${pm} install httping
${pm} install httpry
${pm} install hunspell
${pm} install iperf
${pm} install ipv6calc
${pm} install jam
${pm} install jansson
${pm} install jasper
${pm} install jpeg
${pm} install jrnl
${pm} install jsl
${pm} install jsmin
${pm} install json-c
${pm} install jsonpp
${pm} install launchctl-completion
${pm} install legit
${pm} install llvm --with-clang --with-clang-extra-tools --with-libcxx --with-lld --with-lldb
${pm} install llvm35 --with-lld --with-lldb
${pm} install llvm36 --with-lld --with-lldb
${pm} install llvm37 --with-lld --with-lldb
${pm} install llvm38 --with-lld --with-lldb
${pm} install lrzsz
${pm} install markdown
#${pm} install mscgen --without-gd
${pm} install netcat
${pm} install netperf
${pm} install nmap
${pm} install node
#${pm} install ntfs-3g
${pm} install nuttcp
${pm} install open-completion
${pm} install openocd
#${pm} install osxfuse
${pm} install p0f
${pm} install p7zip
${pm} install parallel
#${pm} install phantomjs
${pm} install pinentry
${pm} install pip-completion
${pm} install pkg-config
${pm} install ruby-completion
${pm} install shellcheck
${pm} install sloccount
${pm} install socat
${pm} install sqlite
${pm} install srecord
${pm} install ssh-copy-id
${pm} install stdman
${pm} install stow
${pm} install stress
${pm} install subgit
${pm} install swig
${pm} install tcpdump
${pm} install tcpflow
${pm} install tcping
${pm} install tcpreplay
${pm} install tcptrace
${pm} install tcptraceroute
${pm} install tcptrack
${pm} install termshare
${pm} install tig
${pm} install tmux
${pm} install tree
${pm} install v8
#${pm} install vegeta
${pm} install vim
${pm} install webp
${pm} install wget
#${pm} install wireshark
${pm} install xctool
${pm} install xmlformat
${pm} install xmlstarlet
${pm} install xmlto

# cleanup
${pm} cleanup -s
