#!/bin/sh
#
# Install Go modules.

set -u

go=$(which go 2> /dev/null)
if [ -z "${go}" -o ! -x "${go}" ]; then
    echo "error: Go not installed, not installing Go packages."
    exit 1
fi

# @todo assume go version >= 1.4

go get -u code.google.com/p/rog-go/exp/cmd/godef
go get -u github.com/nsf/gocode
