#!/bin/sh
#
# Download and bootstrap the indicated version of the Boost C++
# Libraries.

set -u
set -e

if [ $# -ne 1 ]; then
    printf "usage: %s <version>\n" "$(basename "$0")" 1>&2
    exit 1
fi

version="$1"
version_name="$(printf "%s" "${version}" | sed 's/\./_/g')"
root="${HOME}"/opt/local/src/boost
directory=boost_"${version_name}"
filename="${directory}".tar.gz
minor="$(printf "%s" "${version}" | sed 's/^[0-9]\.\([0-9][0-9]\)\.[0-9]/\1/')"

if [ ! -d "${root}" ]; then
    printf "error: %s does not exist.\n" "${root}" 1>&2
    exit 1
fi

if [ -d "${root}"/"${directory}" ]; then
    printf "error: %s already exists.\n" "${root}"/"${directory}" 1>&2
    exit 1
fi

if [ -e "${root}"/"${filename}" ]; then
    printf "error: %s already exists.\n" "${root}"/"${filename} " 1>&2
    exit 1
fi

url=https://boostorg.jfrog.io/artifactory/main/release/"${version}"/source/"${filename}"

wget --no-clobber --output-document "${root}"/"${filename}" "${url}"

if [ ! -e "${root}"/"${filename}" ]; then
    printf "error: %s does not exist.\n" "${root}"/"${filename}" 1>&2
    exit 1
fi

tar xfz "${root}"/"${filename}" -C "${root}"

if [ ! -d "${root}"/"${directory}" ]; then
    printf "error: %s does not exist.\n" "${root}"/"${directory} " 1>&2
    exit 1
fi

cwd="$(pwd)"
cd "${root}"/"${directory}"

./bootstrap.sh
cd "${cwd}"

cat > "${root}"/b2_"${version_name}".sh <<-EOF
	#!/bin/sh
	if [ -n "\${BOOST_BUILD_PATH}" ]; then
	    export BOOST_BUILD_PATH="\${BOOST_BUILD_PATH}":"${root}"/"${directory}"/tools/build
	else
	    export BOOST_BUILD_PATH="${root}"/"${directory}"/tools/build
	fi
	"${root}"/"${directory}"/b2 "\$@"
EOF
chmod a+x "${root}"/b2_"${version_name}".sh
