#!/usr/bin/env python3
#
# Install Rust packages.

import sys
import os
import subprocess
import shutil


def emulate_run(args, env=None):
    p = subprocess.Popen(args, env=env)
    if p.wait() == 0:
        return True
    return False


cargo = shutil.which('cargo')

if __name__ == '__main__':
    if not cargo:
        print('error: Cargo not installed, not installing Rust packages.')
        sys.exit(1)

    error = False
    with open('install_rust_packages.txt', 'r') as f:
        for line in f:
            line = line.strip()
            line = line.rstrip('\n')
            if line != '' and line[0] != '#':
                line = line.split()
                e = os.environ
                if not emulate_run([cargo, 'install', '-v'] + line, env=e):
                    error = True

    sys.exit(1 if error else 0)
