#!/bin/sh
#
# Install interesting Ruby packages from gem.

# check if Ruby is installed
if [ -z "$(which ruby)" ]; then
    echo "error: Ruby not found."
    exit 1
fi

# check if gem is installed
# @todo install gem using normal methods
if [ -z "$(which gem)" ]; then
    echo "error: gem is not found."
    exit 1
fi

# install packages manually
gem install json
gem install lolcat
gem install travis-lint
