#!/usr/bin/env python3
#
# Install Go packages.

import sys
import os
import subprocess
import shutil


def emulate_run(args, env=None):
    p = subprocess.Popen(args, env=env)
    if p.wait() == 0:
        return True
    return False


go = shutil.which('go')

if __name__ == '__main__':
    if not go:
        print('error: Go not installed, not installing Go packages.')
        sys.exit(1)

    error = False
    with open('install_go_packages.txt', 'r') as f:
        for line in f:
            line = line.strip()
            line = line.rstrip('\n')
            if line != '' and line[0] != '#':
                if not emulate_run([go, 'install', line]):
                    error = True

    sys.exit(1 if error else 0)
