#!/usr/bin/env python
#
# Install source packages to ~/opt/local.
#
# This script assumes that all source package dependencies are already
# installed.

import sys
import os
import subprocess
import filecmp
import shutil


def git_clone_update_pull_ff_only(url, directory):
    """Clone, update, and pull --ff-only the given url to the given
    directory.

    """
    if not os.path.exists(directory):
        command = ['git', 'clone', url, directory]
        subprocess.check_call(command)

    command = ['git', '-C', directory, 'pull', '--ff-only']
    subprocess.check_call(command)
    command = ['git', '-C', directory, 'submodule', 'init']
    subprocess.check_call(command)
    command = ['git', '-C', directory, 'submodule', 'update']
    subprocess.check_call(command)


def install_tee3_c_style(basedir):
    git_clone_update_pull_ff_only(
        'https://github.com/tee3/tee3-c-style.git',
        os.path.join(basedir, 'src', 'tee3-c-style'))


def install_msvc_c_style(basedir):
    git_clone_update_pull_ff_only(
        'https://github.com/tee3/msvc-c-style.git',
        os.path.join(basedir, 'src', 'msvc-c-style'))


def install_git_svn_update_externals(basedir):
    git_clone_update_pull_ff_only(
        'https://github.com/tee3/git-svn-update-externals.git',
        os.path.join(basedir, 'src', 'git-svn-update-externals'))

    source = os.path.join(basedir, 'src', 'git-svn-update-externals', 'git-svn-update-externals')
    target = os.path.join(basedir, 'bin', 'git-svn-update-externals')

    if os.path.exists (target):
        if not filecmp.cmp(target, source, False):
            yn = raw_input('%s is different than %s.  Overwrite anyway? (y/n): ' % (source, target))
            if yn == 'y':
                os.remove(target)

    if not os.path.exists (target):
        if hasattr(os, 'symlink'):
            os.symlink(source,target)
        else:
            shutil.copyfile(source,target)


def install_rtags(basedir):
    rtagsdir = os.path.join(basedir, 'src', 'rtags')

    git_clone_update_pull_ff_only(
        'https://github.com/andersbakken/rtags.git',
        rtagsdir)

    command = ['git', '-C', rtagsdir, 'clean', '-d', '-x', '-f']
    subprocess.check_call(command)

    build = os.path.join(rtagsdir, 'Release')
    if not os.path.exists(build):
        os.makedirs(build)

    command = [
        'cmake',
        '..',
        '-DCMAKE_BUILD_TYPE=Release',
        '-DCMAKE_INSTALL_PREFIX:PATH=' + basedir
    ]
    subprocess.check_call(command, cwd=build)
    command = ['make']
    subprocess.check_call(command, cwd=build)
    command = ['make', 'install']
    subprocess.check_call(command, cwd=build)

# requires HOME.
if 'HOME' not in os.environ or os.environ['HOME'] == '':
    print 'error: HOME is not set, aborting.'
    sys.exit(1)
HOME = os.environ['HOME']

# default the prefix to ~/opt/local
prefix = os.path.join(HOME, 'opt', 'local')

if __name__ == '__main__':
    # install desired source packages
    install_tee3_c_style(prefix)
    install_msvc_c_style(prefix)
    install_git_svn_update_externals(prefix)
    if not sys.platform.startswith('win32'):
        install_rtags(prefix)

    sys.exit(0)
