#!/bin/sh
#
# Install bootstrap packages for Debian.
#
# This assumes that the current user is the user used to install
# packages and has the proper administrator privileges.

set -e
set -u

# mDNS
sudo apt-get -q -y install avahi-autoipd avahi-daemon avahi-utils libnss-mdns
# NTP
sudo apt-get -q -y install ntp
# SSH
sudo apt-get -q -y install openssh-client openssh-server
