#!/bin/sh
#
# Install bootstrap packages for OS X.
#
# This assumes that the current user is the user used to install
# packages and has the proper administrator privileges.

set -e
set -u

# Homebrew requirements
if ! xcode-select -p > /dev/null ; then
    xcode-select --install
fi

printf "Install Xcode from the App Store and press Enter when complete: "
read -r

# Homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
