#!/bin/sh
#
# Install interesting packages for Fedora.
#
# This assumes that the current user is the user used to install
# packages.  and has the proper administrator privileges.

# additional repositories
#! @todo none right now

# check if yum is installed
if [ -z "$(which yum 2> /dev/null)" ]; then
    echo "error: yum not found."
    exit 1
fi

# update and check packages
sudo yum check

# upgrade existing packages
sudo yum update

# install packages for homedir installer
sudo yum install wget
sudo yum install stow
sudo yum install diffutils

# install interpreters prior to other packages
sudo yum install python
# @todo we don't need python3 at this point
#sudo yum install python3
sudo yum install ruby

# install version control systems
sudo yum install git
sudo yum install mercurial
sudo yum install subversion

# install all taps with the right options
#sudo yum install arp-scan
#sudo yum install arp-sk
#sudo yum install arpoison
#sudo yum install autoconf
#sudo yum install automake
#sudo yum install avrdude
#sudo yum install avr-binutils
#sudo yum install avr-gcc
sudo yum install bash-completion
#sudo yum install boost
#sudo yum install boost-bcp
#sudo yum install boost-build
#sudo yum install casperjs
#sudo yum install clang-format
#sudo yum install cmake
#sudo yum install cppcheck
#sudo yum install dart
#sudo yum install dns2tcp
#sudo yum install dnstop
#sudo yum install docbook
#sudo yum install docbook-xsl
#sudo yum install docker
#sudo yum install doxygen
#sudo yum install e2fsprogs
#sudo yum install emacs
#sudo yum install emscripten
#sudo yum install enscript
#sudo yum install ext2fuse
#sudo yum install fop
#sudo yum install fortune
#sudo yum install apple-gcc42
#sudo yum install gcc
#sudo yum install gcc43
#sudo yum install gcc44
#sudo yum install gcc45
#sudo yum install gcc46
#sudo yum install gcc47
#sudo yum install gcc48
#sudo yum install gcc49
#sudo yum install git-flow
#sudo yum install git-hooks
#sudo yum install glew
#sudo yum install glfw3
#sudo yum install glib
#sudo yum install glm
#sudo yum install global
#sudo yum install gnu-typist
#sudo yum install golang
#sudo yum install gource
#sudo yum install graphviz
#sudo yum install guile
#sudo yum install highlight
#sudo yum install htop-osx
#sudo yum install httping
#sudo yum install httpry
#sudo yum install hunspell
#sudo yum install iperf
#sudo yum install ipv6calc
#sudo yum install jam
#sudo yum install jansson
#sudo yum install jasper
#sudo yum install jpeg
#sudo yum install jsdoc-toolkit
#sudo yum install jsl
#sudo yum install jsmin
#sudo yum install json-c
#sudo yum install jsonpp
#sudo yum install legit
#sudo yum install llvm
#sudo yum install llvm31
#sudo yum install llvm32
#sudo yum install llvm33
#sudo yum install llvm34
#sudo yum install llvm35
#sudo yum install markdown
#sudo yum install multimarkdown
#sudo yum install mscgen
#sudo yum install netcat
#sudo yum install netperf
#sudo yum install nmap
#sudo yum install node
#sudo yum install nuttcp
#sudo yum install ntfs-3g
#sudo yum install osxfuse
#sudo yum install nuttcp
#sudo yum install p0f
#sudo yum install p7zip
#sudo yum install parallel
#sudo yum install phantomjs
#sudo yum install pinentry
#sudo yum install pkg-config
#sudo yum install shellcheck
#sudo yum install socat
#sudo yum install sqlite
#sudo yum install srecord
#sudo yum install ssh-copy-id
#sudo yum install sshfs
#sudo yum install stow
#sudo yum install stress
#sudo yum install subgit
#sudo yum install swig
#sudo yum install tcpdump
#sudo yum install tcpflow
#sudo yum install tcping
#sudo yum install tcpreplay
#sudo yum install tcptrace
#sudo yum install tcptraceroute
#sudo yum install tcptrack
#sudo yum install termshare
#sudo yum install tig
#sudo yum install tmux
#sudo yum install tree
#sudo yum install v8
#sudo yum install webp
#sudo yum install wget
#sudo yum install wireshark
#sudo yum install xctool
#sudo yum install xmlformat
#sudo yum install xmlstarlet
#sudo yum install xmlto

# cleanup
sudo yum autoremove
sudo yum clean all
