#!/bin/sh
#
# Install Ruby modules in the ruby-packages.gemfile Gemfile.

set -u

ruby=$(which ruby 2> /dev/null)
if [ -z "${ruby}" -o ! -x "${ruby}" ]; then
    echo "error: Ruby not installed, not installing Ruby packages."
    exit 1
fi

gem=$(which gem 2> /dev/null)
if [ -z "${gem}" -o ! -x "${gem}" ]; then
    echo "error: gem is not available, skipping Ruby module installation"
    exit 1
fi

# location of gems with --user-install
gemdir=~/.gem

${gem} install --user-install bundler

bundle="$(ruby -rubygems -e 'puts Gem.user_dir')"/bin/bundle
if [ -z "${bundle}" -o ! -x "${bundle}" ]; then
    echo "error: failed to install bundler, skipping Ruby module installation"
    exit 1
fi

${bundle} install --path "${gemdir}" --gemfile=ruby-packages.gemfile
