#!/bin/sh
#
# Install bootstrap packages for Fedora.
#
# This assumes that the current user is the user used to install
# packages and has the proper administrator privileges.

set -e
set -u

# mDNS
sudo yum -q -y install avahi avahi-tools nss-mdns
# NTP
sudo yum -q -y install install ntp
# SSH
sudo yum -q -y install openssh openssh-server
