#!/bin/sh
#
# Install Ruby modules in the ruby-packages.gemfile Gemfile.

set -u

ruby=$(which ruby 2> /dev/null)
if [ -z "${ruby}" ] || [ ! -x "${ruby}" ]; then
    echo "error: Ruby not installed, not installing Ruby packages."
    exit 1
fi

gem=$(which gem 2> /dev/null)
if [ -z "${gem}" ] || [ ! -x "${gem}" ]; then
    echo "error: gem is not available, skipping Ruby module installation"
    exit 1
fi

# location of gems with --user-install
gemdir="$(ruby -rubygems -e 'puts Gem.user_dir')"

${gem} install --user-install --bindir="${gemdir}"/bin --file ruby-packages.gemfile
