#!/usr/bin/env python
#
# Install Ruby modules in the ruby-packages.gemfile Gemfile.

import sys
import os
import subprocess
import distutils.spawn


def emulate_run(args, env=None):
    p = subprocess.Popen(args, env=env)
    if p.wait() == 0:
        return True
    return False


def emulate_backtick(args):
    try:
        output = subprocess.check_output(args).rstrip("\n")
    except:
        output = ""

    return output

HOME = os.environ["HOME"]

ruby = distutils.spawn.find_executable("ruby")
if not ruby:
    print "error: Ruby not installed, not installing Ruby packages."
    sys.exit(1)

gem = distutils.spawn.find_executable("gem")
if not gem:
    print "error: gem is not available, skipping Ruby module installation"
    sys.exit(1)

# location of gems with --user-install
gemdir = emulate_backtick([ruby, "-rubygems", "-e", "puts Gem.user_dir"])

sys.exit(emulate_run([gem, "install", "--user-install", "--bindir", os.path.join(gemdir, "bin"), "--file", "ruby-packages.gemfile"]))
