#!/bin/sh
#
# Install bootstrap packages for Debian.
#
# This assumes that the current user is the user used to install
# packages and has the proper administrator privileges.

set -e
set -u

# Homebrew requirements
sudo apt-get install build-essential curl file git

# Homebrew
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
